# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Forg5fiYPwxQE-J2-DvWn1ZzrU_s_Boz
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

tickers=["HDFCBANK.NS","ICICIBANK.NS","KOTAKBANK.NS"]
data= yf.download(tickers,start="2024-01-01",end="2024-12-30",group_by='tickers')
hdfc_data=data['HDFCBANK.NS']
hdfc_data['Daily_Return']=hdfc_data['Close'].pct_change()
plt.figure(figsize=(12,6))
plt.subplot(2,1,1)
hdfc_data['Close'].plot(title="HDFC_CP")
plt.subplot(2,1,2)
hdfc_data['Daily_Return'].plot(title="hdfc_daily_returns",color='orange')
plt.tight_layout()
plt.show()

icic_data=data['HDFCBANK.NS']
icic_data['Daily_Return']=icic_data['Close'].pct_change()
plt.figure(figsize=(12,6))
plt.subplot(2,1,1)
icic_data['Close'].plot(title="ICICI_CP")
plt.subplot(2,1,2)
icic_data['Daily_Return'].plot(title="icici_daily_returns",color='orange')
plt.tight_layout()
plt.show()